name: Trigger Site Rebuild on a CRON Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST ${{ secrets.VERCEL_WEBHOOK }}
